export const COUNTRIES = [
  "United States",
  "Canada",
  "United Kingdom",
  "Australia",
  "Germany",
  "France",
  "Japan",
  "South Korea",
  "Singapore",
  "United Arab Emirates",
  "Mexico",
  "Brazil",
  "India",
  "Netherlands",
  "Switzerland",
  "Sweden",
  "Norway",
  "Denmark",
  "Spain",
  "Italy",
  "New Zealand",
  "Ireland",
  "Belgium",
  "Austria",
  "Portugal",
  "Poland",
  "Philippines",
  "Hong Kong",
  "Taiwan",
  "Thailand",
  "Malaysia",
  "Maldives",
  "Mali",
  "Indonesia",
  "South Africa",
  "Argentina",
  "Chile",
  "Colombia",
  "Israel",
  "Saudi Arabia",
  "Turkey",
  "Other",
] as const;
